# 1.Print 'Hello HCIA'.

In [2]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [4]:
a=5
b=6
c=a+b
print(c)

11


# 3.Define a list and replicate in three different ways.

In [2]:
a=[3,4,5]
b=[]
c= a 
for i in a:
    b.append(i)
d=a.copy()


# 4.Define two lists and merge them together.

In [1]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


# 5. Get the last element of the list and print it.

In [3]:
print(a[len(a)-1])

3


# 6.Define a tuple that contains only one element.

In [ ]:
tup = (1)


# 7.Define a three-line long string.

In [4]:
long_string = r'''one
two
three'''
print(long_string)

one
two
three


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [5]:
tup = (1,2,3,4,5,6)
for i in tup:
    print(i)

1
2
3
4
5
6


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [6]:
def Mul(a,b):
    return a*b
print(Mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [7]:
import numpy as np 
a = np.zeros((5,5))


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [8]:
import numpy as np 
a = np.zeros((4,6))

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [15]:
c = np.arange(15,)
c.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [22]:
a = np.array([[ 0,  1,  2],
              [ 5,  6,  7],
              [10, 11, 12]])
b = np.array([[ 2, 3,  4],
              [ 5,  6,  7],
              [13, 13, 13]])
print(np.dot(a,b))

[[ 31  32  33]
 [131 142 153]
 [231 252 273]]
